version: '2'
services:
  mariadb:
    ports:
      - '33306:3306'
    image: docker.io/bitnami/mariadb:10.6
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=no
      - MARIADB_USER=bn_wordpress
      - MARIADB_PASSWORD=${MDBWPPW}
      - MARIADB_DATABASE=bitnami_wordpress
      - MARIADB_ROOT_PASSWORD=${MDBRTPW}
  wordpress:
    image: docker.io/bitnami/wordpress:6
    ports:
      - '3280:8080'
      - '32443:8443'
    volumes:
      - 'wordpress_data:/bitnami/wordpress'
    depends_on:
      - mariadb
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=no
      - WORDPRESS_DATABASE_HOST=mariadb
      - WORDPRESS_DATABASE_PORT_NUMBER=3306
      - WORDPRESS_DATABASE_USER=bn_wordpress
      - WORDPRESS_DATABASE_PASSWORD=${MDBWPPW}
      - WORDPRESS_DATABASE_NAME=bitnami_wordpress
      - WORDPRESS_USERNAME=hcc-sysop
      - WORDPRESS_PASSWORD=${WPPW}
volumes:
  mariadb_data:
    driver: local
  wordpress_data:
    driver: local
